# Generated by Django 4.2.1 on 2023-07-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselingdate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='show',
            new_name='CounselingDate',
        ),
    ]
