# Generated by Django 4.2.1 on 2023-07-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
        ('counselingdate', '0002_rename_show_counselingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingdate',
            name='counseling',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='counseling.counseling'),
        ),
        migrations.AlterField(
            model_name='counselingdate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
