# Generated by Django 4.2.1 on 2023-08-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselingdate', '0004_remove_counselingdate_counseling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('counseling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselingdate.counselingdate')),
            ],
        ),
    ]
