# Generated by Django 4.2.1 on 2023-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
