# Generated by Django 4.2.1 on 2023-07-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselingdate', '0004_remove_counselingdate_counseling_and_more'),
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counseling',
            name='counseling',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='counselingdate.counselingdate'),
        ),
    ]
