# Generated by Django 4.2.1 on 2023-08-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_counseling_counseling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counseling',
            name='time',
        ),
    ]
