# Generated by Django 4.2.1 on 2023-08-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselingdate', '0005_counselingtime'),
        ('counseling', '0003_remove_counseling_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='counseling',
            name='counseling_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_session', to='counselingdate.counselingtime'),
        ),
    ]
